#!/usr/bin/env bash
# Packages that should be installed
pkgs="alpine-base bash util-linux bind-tools shadow"
# Services that should be enabled
services=""
# Alpine version
version="v3.10"
# rootfsversion
rootfsversion="3.10.1"
# Location to copy /lib/modules from
modules="/var/empty"
# Directory that will be copied over root dir
overlay="/var/empty"
# Scripts to be executed before building cpio archive
pre_build_hooks=""
