#!/usr/bin/env bash
HERE="$(dirname "$(realpath "$0")")"
docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock -v "$HERE:/work" -w /work alpine sh -c 'apk add docker cpio bash && bash /work/alpes '"'$1'"
