#!/usr/bin/env bash
CONFIG_DIR="$(dirname "${CONFIG}")";

. "${CONFIG_DIR}/../alpes-config";

# Packages that should be installed
pkgs+=" iptables docker linux-firmware-bnx2"
# Services that should be enabled
services+="docker"
# Directory that will be copied over root dir
overlay="${CONFIG_DIR}/docker/overlay"
# Scripts to be executed before building cpio archive
pre_build_hooks=${CONFIG_DIR}/docker/hooks/*

# Hooks config
# ---
# Docker images to import for the boot image
docker_import="redis:alpine"
# Script to run once dockerd is booted
docker_run="${CONFIG_DIR}/docker/files/docker-run"
